### ISSUE TITLE
Loading screen required

### ISSUE THREAD

**Issue by mr-palindrome** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#10]
The current loading animation is not much impressive. 
Add a new loading animation which will also work properly.
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/56421861/194780990-2cf722e8-c63e-4d6e-8ab7-e6bebc4ef4b8.png">

**Comment by REX-HERE** [comment]
i am interested in this, please assign this to me

**Comment by mr-palindrome** [comment]
Thanks for showing interest @REX-HERE.
I'm assigning this issue to you.
