### ISSUE TITLE
Resizing vertically, the height of card are reduced vertically.

### ISSUE THREAD

**Issue by nirajpdn** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#16]
Here is a screenshot.
![2022-10-10_06-19](https://user-images.githubusercontent.com/59108522/194787149-bbd179de-1891-4ce0-b4ca-339f1bb3b16e.png)

**Comment by Nayan-Solytics** [comment]
Hey @nirajpdn! The website is not responsive yet. And we are planning to make it responsive. But for that we need the UI first. If you want to work on this part then I'll assign you. But start working on this ones the UI is available, then it will be better.

**Comment by nirajpdn** [comment]
@mr-palindrome , i will make it little responsive and try to improvise the card design and will fix the height issue. Assign this issue to me.
