### ISSUE TITLE
Acknowledge the Contributors by adding Contributors Section in README.md

### ISSUE THREAD

**Issue by mr-palindrome** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#18]
### Proposed Changes

- Add a dynamic Contributors Section in README file
- Add Copyright Logo to the Project at end of README
- Add more helpful links for beginners in Contributing.md (if needed)

**Comment by najeebkp** [comment]
Hi @mr-palindrome please assign this to me

**Comment by mr-palindrome** [comment]
> Hi @mr-palindrome please assign this to me

Yeah sure!
Keep in mind the section should be dynamic!
