### ISSUE TITLE
Enhance the ui and logic behind start date and end date

### ISSUE THREAD

**Issue by mr-palindrome** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#19]
### Propose changes
- Enhance the start date and end date ui and add a logic which will not allow one to select a date which is less than the start date.
- Change the react logic behind the date
<img width="613" alt="image" src="https://user-images.githubusercontent.com/56421861/194826562-da71d5a0-814c-450b-b049-2ee61ac9edfa.png">
we want something like this:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/56421861/194826848-dce5092e-4927-4620-8929-6efca1fab3f2.png">

**Comment by nirajpdn** [comment]
Alright, i am ready to do this.

**Comment by Dhruv031003** [comment]
Yeah go ahead!

**Comment by Dhruv031003** [comment]
@nirajpdn Any Updates??

**Comment by nirajpdn** [comment]
@Dhruv031003  I will push today

**Comment by nirajpdn** [comment]
@Dhruv031003 @mr-palindrome, so now we have two seperate fields for startDate and endDate.  I should work in seperate fields and fix the logic or i have to use only one field provided by date range picker as shown in image above.

**Comment by Dhruv031003** [comment]
@nirajpdn 
You can use two fields or one it's upto you. But make sure we have option to select both start date and end date,
And one should not be able to select a start date less than end date and end date greater than start date.

**Comment by nirajpdn** [comment]
> @nirajpdn You can use two fields or one it's upto you. But make sure we have option to select both start date and end date, And one should not be able to select a start date less than end date and end date greater than start date.

Alright, thanks

**Comment by Dhruv031003** [comment]
@nirajpdn 
any updates??

**Comment by alexsam29** [comment]
Hi, I can work on this issue if the other person isn't responding.  I feel like it's related to #37, which I also worked on.

**Comment by Dhruv031003** [comment]
Hi @alexsam29
Yeah sure you can work on this.
Just wait till I merge #43
- He made some changes in the date-picker while updating the UI but it has some issues.
- We still have to select the start date and end date seperately. So you can make it such that we can select both by opening the date picker once.

**Comment by Dhruv031003** [comment]
@alexsam29 
You can start your work now.
