### ISSUE TITLE
Loader Lagging || Multiple Loader Renders || No error handling of APIs

### ISSUE THREAD

**Issue by salilgupta2510** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#25]
Hi,

Below are the issues observed:
1. I have observed the loader renders twice, also it is Lagging (not smooth)
2. No error handling for APIs.

Proposed changes:

1. Will add a bootstrap loader to have consistency throughout the project. (https://getbootstrap.com/docs/4.4/components/spinners/)
2. Will add error handling for API resolution and remove redundant code.

**Comment by mr-palindrome** [comment]
Hey @salilgupta2510!
Thanks for showing interest.
I'm assigning this to you. But please keep in mind there is already an issue(#10  ) to change the loader gif. So, it would be better if you don't add any new loader, or you can add a gif loader.

**Comment by salilgupta2510** [comment]
Hey, @mr-palindrome thanks for assigning this to me.
I went through issue #10, no PR has come in yet for that fix.
I have the code ready for replacement with a Bootstrap CSS loader(link attached in the issue described above), so should i go ahead with that change as well?

**Comment by mr-palindrome** [comment]
> Hey, @mr-palindrome thanks for assigning this to me. I went through issue #10, no PR has come in yet for that fix. I have the code ready for replacement with a Bootstrap CSS loader(link attached in the issue described above), so should i go ahead with that change as well?

There was a PR which has been closed #14 which I reverted later on #17 .
But there is another PR which is expected to come soon on that.
You can have a look over the discussion on those PRs.

**Comment by salilgupta2510** [comment]
Ohkay, in that case i will remove my code for the loader replacement.
