### ISSUE TITLE
UI Change: Update the navbar as per the new UI

### ISSUE THREAD

**Issue by mr-palindrome** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#33]
- There is an UI change. The ui is available in the readme section as well as the Figma link is also available. 
- The functionality of the navbar should be untouched. The fonts and colours should be matched with the UI.
- The logo is also available in the ui folder.

**Comment by photon0205** [comment]
I would like to work on this issue, can you assign it to me?

**Comment by Dhruv031003** [comment]
@photon0205 
Yes you can work on this
