### ISSUE TITLE
Calender date change

### ISSUE THREAD

**Issue by Dhruv031003** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#34]
![image](https://user-images.githubusercontent.com/91516121/195665483-8c15e11b-12c9-4072-92bb-a2ecb4f9aece.png)

### Issue
- When any of these arrows are pressed the date updates which results in loading of new tweets.

This should not happen.
The date should change only when a particular date is selected form the calender rather than on clicking the arrows.

**Comment by alexsam29** [comment]
Hi, I might have an idea on how to fix this.  If you assign it to me I'll give it a shot!

**Comment by Dhruv031003** [comment]
@alexsam29 
Hi, you can work on this.

**Comment by alexsam29** [comment]
Great, will have a PR soon.
