### ISSUE TITLE
Work from home input change

### ISSUE THREAD

**Issue by Dhruv031003** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#35]
Work From Home input is currently a Dropdown type we want it as a checkbox.
- On checked state it's value should be true and in unchecked state value should be false.

**Comment by zachyo** [comment]
I want to work on this issue

**Comment by Dhruv031003** [comment]
Yeah sure, you can start your work

**Comment by Dhruv031003** [comment]
@zachyo any updates??

**Comment by Dhruv031003** [comment]
@zachyo you still on this??

**Comment by photon0205** [comment]
I can work on this issue. Can you assign it to me?

**Comment by Dhruv031003** [comment]
@photon0205 
Okay you can work on this.
