### ISSUE TITLE
Navbar input fix

### ISSUE THREAD

**Issue by Dhruv031003** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#38]
![image](https://user-images.githubusercontent.com/91516121/196005121-b3bcc86b-1466-4b82-be84-acde566d427a.png)
There is an white extra background behind this input field.
Fix this issue.

**Comment by Siyayadav** [comment]
@Dhruv031003 I would like to work on this issue

**Comment by Dhruv031003** [comment]
@Siyayadav Yes go ahead.
