### ISSUE TITLE
Unwanted margin in Input

### ISSUE THREAD

**Issue by Dhruv031003** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#44]
![image](https://user-images.githubusercontent.com/91516121/197395744-97bac901-fb14-4c33-8af7-11ecb707bcce.png)
- There is a very small margin of arnd 2px around the inputs which creates a small space which doesn't look good.
- Remove the margin, the issue happes with all four inputs.

**Comment by photon0205** [comment]
I would like to take this issue

**Comment by Dhruv031003** [comment]
@photon0205 
All yours.
