### ISSUE TITLE
Navbar width

### ISSUE THREAD

**Issue by Dhruv031003** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#50]
![image](https://user-images.githubusercontent.com/91516121/198185846-8afca487-c54e-4f7c-867d-cadf47bbd604.png)
- Navbar should cover the whole Viewport width.

**Comment by Halim-Shams** [comment]
I can solve that issue, assign this to me

**Comment by srijoy-paul** [comment]
Hey @Dhruv031003 can you assign me this task? Would love to work on this

**Comment by Mayureshkaulwar** [comment]
please assign to me

**Comment by Dhruv031003** [comment]
@srijoy-paul 
You can work on this issue since another is already assigned to @Halim-Shams.

**Comment by srijoy-paul** [comment]
@Dhruv031003 working on it

**Comment by srijoy-paul** [comment]
@Dhruv031003 is this issue already solved, as the navbar seems to be as it was required?

**Comment by Dhruv031003** [comment]
@srijoy-paul 
No it's not fixed. You have to change the viewport width to see the issue.
