### ISSUE TITLE
Alignment of Tweetcontainer

### ISSUE THREAD

**Issue by Dhruv031003** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#51]
![image](https://user-images.githubusercontent.com/91516121/198186025-171657f9-6e19-42aa-8754-72b6714a07f0.png)
`Tweecontainer` is not centered w.r.t "Job Tweets" heading
- Align `TweetContainer` properly
- `TweetContainer` width should not exceed the width of it's heading

**Comment by Halim-Shams** [comment]
i can work on this issue.

**Comment by srijoy-paul** [comment]
Hey @Dhruv031003 I can complete this asap, Can you assign me this?

**Comment by Mayureshkaulwar** [comment]
please assign to me

**Comment by Dhruv031003** [comment]
I am assigning this to @Halim-Shams since he asked first.
