### ISSUE TITLE
More selection required.

### ISSUE THREAD

**Issue by mr-palindrome** [Google-Developer-Student-Club-RJIT/remotebirdjobs-frontend#9]
Currently this selection has only few limited fields.
But we need more such fields like Java, Spring, MERN, NodeJS, etc.
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/56421861/194780834-7ef6547d-f430-4568-a03f-642910aacf5c.png">

**Comment by photon0205** [comment]
We just have to add more fields in the selection?

**Comment by mr-palindrome** [comment]
> We just have to add more fields in the selection?

Right!

**Comment by photon0205** [comment]
Hi, I am ready to work on this. Please assign me this issue

**Comment by mr-palindrome** [comment]
Yeah sure!

**Comment by mr-palindrome** [comment]
> Hi, I am ready to work on this. Please assign me this issue

It would be better if you can create something like this:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/56421861/194808103-851cdf19-3a76-4435-9cca-6a27c75ef138.png">

You can find this on https://github.com/trending

**Comment by nirajpdn** [comment]
Please assign this to me as well.

**Comment by mr-palindrome** [comment]
> Please assign this to me as well.

This one is already assigned. Till then you can work on other issues.
You can enhance the start date and end date ui and add a logic which will not allow any one to select a date list than the start date!

**Comment by nirajpdn** [comment]
Okay assign that issue to me

**Comment by mr-palindrome** [comment]
> Okay assign that issue to me

#19 Please reply here! so that I can assign you!

**Comment by photon0205** [comment]
I have improved the selection and raised a pr
You can review #24
